### ISSUE TITLE
jOOQ Kotlin-specific configuration flags seem to have no effect

### ISSUE THREAD

**Issue by n0rdy** [monosoul/jooq-gradle-plugin#250] opened 2024-12-20 09:30 UTC
Hello there!

First of all, thanks a lot for creating this plugin, it was very straightforward to set it up using the guidance provided in the README file and examples section. Great job! =)

For my toy project, I'm using Kotlin, jOOQ, Flyway and Gradle combination, with this plugin on top to generate jOOQ code.
By default, jOOQ marks all the Kotlin data classes fields as nullable, regardless whether `NOT NULL` is present in the DB schema, for example:
```
val ID: TableField<UsersRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")
```
where you can see the `UUID?` despite the fact that this field is a primary key and not nullable.

or

```
val NAME: TableField<UsersRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")
```
with the `name         TEXT        NOT NULL,` SQL definition

However, starting from version 3.18, [it is possible](https://github.com/jOOQ/jOOQ/issues/10212#issuecomment-1252351193) to change this behavior (here is the [jOOQ doc](https://www.jooq.org/doc/latest/manual/code-generation/kotlingenerator/))

My attempts to configure this via `jooq-gradle-plugin` didn't have any effect, so I'd like to double-check whether there is a chance that plugin somehow is not aware of these Kotlin-specific flags, and, therefore, doesn't pass them forward or override them with default values.

Things I tried:
- `usingJavaConfig`:
```
usingJavaConfig {
    // to generate Kotlin classes instead of Java ones
    name = "org.jooq.codegen.KotlinGenerator"

    generate.withKotlinNotNullPojoAttributes(true)
        .withKotlinNotNullRecordAttributes(true)
        .withKotlinNotNullInterfaceAttributes(true)
}
```
The `name` property makes an effect. Also, if I add, for example, `.withGeneratedAnnotationDate(true)`, I see that the generated code changes by adding a date to the `@Generated` annotation, which means that the configurations have been passed correctly

- `usingXmlConfig`:
```
usingXmlConfig()
```
and here is the `jooq.xml` file located in `/resources/db` folder:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.19.8.xsd">
    <generator>
        <!-- Generate Kotlin classes instead of Java ones -->
        <name>org.jooq.codegen.KotlinGenerator</name>
        <database>
            <inputSchema>public</inputSchema>
        </database>
        <generate>
            <!-- Generate non-nullable types on POJO attributes, where column is not null. Default is false. -->
            <kotlinNotNullPojoAttributes>true</kotlinNotNullPojoAttributes>

            <!-- Generate non-nullable types on Record attributes, where column is not null. Default is false. -->
            <kotlinNotNullRecordAttributes>true</kotlinNotNullRecordAttributes>

            <!-- Generate non-nullable types on interface attributes, where column is not null. Default is false. -->
            <kotlinNotNullInterfaceAttributes>true</kotlinNotNullInterfaceAttributes>
        </generate>
    </generator>
</configuration>
```

Playing with other flags of `<generate>` object made a noticeable effect, but not the Kotlin nullability-related ones.

Thanks.

**Comment by monosoul** [comment] 2024-12-21 11:23
Hey @n0rdy , you're confusing `records` with `tables` here. jOOQ will generate non-nullabe records for you, but for table fields it is problematic to have non-nullable fields, since you can get nulls there when you do table joins for examples.
@lukaseder explained that in one of the issues iirc.

**Comment by monosoul** [comment] 2024-12-21 11:30
I've added an example with Kotlin data classes here: https://github.com/monosoul/jooq-gradle-plugin/pull/253/commits/946fb60ed0ffa412d691049bf5ca6e621c5502be

If you'll check generated `FooRecord`, it will have both `id` and `data` properties an non-nullable:
```kotlin
open class FooRecord private constructor() : UpdatableRecordImpl<FooRecord>(Foo.FOO) {

    open var id: UUID
        set(value): Unit = set(0, value)
        get(): UUID = get(0) as UUID

    open var `data`: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String
```

**Comment by monosoul** [comment] 2024-12-21 11:35
You can technically achieve what you want with custom type mappings, but then again, you might face issues writing queries later on, so I wouldn't recommend doing so.
I'll close the issue now as the plugin itself works as intended.

**Closed by monosoul** 2024-12-21 11:35 UTC

**Comment by n0rdy** [comment] 2024-12-21 11:49
You are absolutely right, my apologies for the confusions.

**Comment by monosoul** [comment] 2024-12-21 11:50
No worries ☺️
